# Generated by Django 4.1.4 on 2022-12-26 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_entity', '0002_alter_entity_properties'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='properties',
            field=models.ManyToManyField(to='app_entity.property'),
        ),
    ]
